version: '3.1'

services:
  db:
    build:
      context: .   
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - my_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  my_pgdata:
